server:
  port: 9529
spring:
  application:
    name: question-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9527/eureka/
feign:
  hystrix:
    #开启feign的hystrix支持,默认是false
    enabled: true
logging:
  level:
    com.hydu: debug
zuul:
#  prefix: /api # 添加路由前缀
  routes:
      user-service: # 这里是路由id，随意写
        path: /user-service/** # 这里是映射路径
        service-id: user-service # 指定服务名称
